[tox]
envlist = py38, py39, py310, py311, py312
skip_missing_interpreters = true

[testenv]
deps =
    -e .[dev,server]
commands =
    pytest --cov=aicortex --cov-report=term-missing
    mypy aicortex
    black --check aicortex tests
    flake8 aicortex tests

[testenv:docs]
deps =
    -e .[dev]
    sphinx
    sphinx-rtd-theme
commands =
    sphinx-build -b html docs docs/_build/html

[testenv:build]
deps =
    build
    twine
commands =
    python -m build
    twine check dist/*